language: csharp

os: linux

sudo: required
dist: bionic

dotnet: 2.2.105
mono: none

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

addons:
  ssh_known_hosts: github.com

before_install:
  - chmod +x travis/fix-branches.sh
  - "./travis/fix-branches.sh"

before_script:
  - chmod +x build.sh

script:
  - "./build.sh -t Travis"

cache:
  directories:
    - tools
    - $HOME/.nuget/packages
